//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsAspur
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public string pec_id { get; set; }
        public Nullable<float> napatie { get; set; }
        public Nullable<float> prud { get; set; }
        public Nullable<float> sobert_vstup { get; set; }
        public Nullable<float> t_voda_vstup { get; set; }
        public Nullable<float> t_voda_vystup { get; set; }
        public Nullable<float> vykon { get; set; }
        public Nullable<float> rz_pribenie { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<float> sobert_vykon { get; set; }
        public Nullable<float> tlak { get; set; }
        public string zmena { get; set; }
    }
}
