//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsAspur
{
    using System;
    using System.Collections.Generic;
    
    public partial class report2s
    {
        public int ID { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public string SHIFT { get; set; }
        public string R1_B { get; set; }
        public string R1_S { get; set; }
        public string R1_F { get; set; }
        public string R2_B { get; set; }
        public string R2_S { get; set; }
        public string R2_F { get; set; }
        public Nullable<float> OK_ { get; set; }
        public Nullable<float> NOK_ { get; set; }
        public Nullable<int> CNT_OK { get; set; }
        public Nullable<int> CNT_NOK { get; set; }
        public Nullable<int> UR1 { get; set; }
        public Nullable<int> UR2 { get; set; }
        public Nullable<float> R1_ { get; set; }
        public Nullable<float> R2_ { get; set; }
        public string ERROR { get; set; }
        public Nullable<float> ERROR_TIME { get; set; }
        public Nullable<float> CYCLE_TIME { get; set; }
        public Nullable<float> WAITING_TIME { get; set; }
    }
}
